# Generated by Django 3.0 on 2020-01-03 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20191231_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.PositiveIntegerField(choices=[(2, '未审核'), (1, '正常'), (0, '删除')], default=2, verbose_name='状态'),
        ),
    ]
